version: '3'

services:

  mongo:
    image: mongo
    restart: always
    networks:
      - bangernet

  bangerbot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    networks:
      - bangernet
    environment:
      - BOT_TOKEN=1425299125:AAFh6htrQ8UysssX66UyQq87oanCqNPF2FA
        
networks:
  bangernet:
    driver: bridge
