name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest and coverage
        run: |
          coverage run --omit="*/tests*" --source=. -m pytest tests/unit -s
      - name: coverage.py badge
        uses: tj-actions/coverage-badge-py@v1.6
        with:
          # Output path to write the badge.
          output: docs/coverage.svg
          overwrite: true
